// This file is auto-generated by src/scripts/generate-component-map.mts
  // Do not edit this file directly
  
  export interface ComponentInfo {
    path: string | null;
    category: string;
    type: string;
    displayName: string;
    href: string;
    sections: Array<{ id: string; title: string }>;
  }
  
  export type ComponentMap = Record<string, ComponentInfo>
  
  export const componentMap: ComponentMap = {
    "accordion": {
      path: "src/components/xfork-ui/accordion.tsx",
      category: "components",
      type: "ui",
      displayName: "Accordion",
      href: "/docs/accordion",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"}]
    },
  "alert-dialog": {
      path: "src/components/xfork-ui/alert-dialog.tsx",
      category: "components",
      type: "ui",
      displayName: "Alert Dialog",
      href: "/docs/alert-dialog",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"}]
    },
  "alert": {
      path: "src/components/xfork-ui/alert.tsx",
      category: "components",
      type: "ui",
      displayName: "Alert",
      href: "/docs/alert",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"}]
    },
  "aspect-ratio": {
      path: "src/components/xfork-ui/aspect-ratio.tsx",
      category: "components",
      type: "ui",
      displayName: "Aspect Ratio",
      href: "/docs/aspect-ratio",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"}]
    },
  "avatar": {
      path: "src/components/xfork-ui/avatar.tsx",
      category: "components",
      type: "ui",
      displayName: "Avatar",
      href: "/docs/avatar",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"}]
    },
  "badge": {
      path: "src/components/xfork-ui/badge.tsx",
      category: "components",
      type: "ui",
      displayName: "Badge",
      href: "/docs/badge",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"}]
    },
  "breadcrumb": {
      path: "src/components/xfork-ui/breadcrumb.tsx",
      category: "components",
      type: "ui",
      displayName: "Breadcrumb",
      href: "/docs/breadcrumb",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"}]
    },
  "button": {
      path: "src/components/xfork-ui/button.tsx",
      category: "components",
      type: "ui",
      displayName: "Button",
      href: "/docs/button",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"link","title":"Link"},{"id":"examples","title":"Examples"},{"id":"changelog","title":"Changelog"}]
    },
  "calendar": {
      path: "src/components/xfork-ui/calendar.tsx",
      category: "components",
      type: "ui",
      displayName: "Calendar",
      href: "/docs/calendar",
      sections: [{"id":"about","title":"About"},{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"date-picker","title":"Date Picker"},{"id":"examples","title":"Examples"},{"id":"changelog","title":"Changelog"}]
    },
  "card": {
      path: "src/components/xfork-ui/card.tsx",
      category: "components",
      type: "ui",
      displayName: "Card",
      href: "/docs/card",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"},{"id":"changelog","title":"Changelog"}]
    },
  "carousel": {
      path: "src/components/xfork-ui/carousel.tsx",
      category: "components",
      type: "ui",
      displayName: "Carousel",
      href: "/docs/carousel",
      sections: [{"id":"about","title":"About"},{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"},{"id":"options","title":"Options"},{"id":"api","title":"API"},{"id":"events","title":"Events"},{"id":"plugins","title":"Plugins"}]
    },
  "chart": {
      path: "src/components/xfork-ui/chart.tsx",
      category: "components",
      type: "ui",
      displayName: "Chart",
      href: "/docs/chart",
      sections: [{"id":"component","title":"Component"},{"id":"installation","title":"Installation"},{"id":"your-first-chart","title":"Your First Chart"},{"id":"chart-config","title":"Chart Config"},{"id":"theming","title":"Theming"},{"id":"tooltip","title":"Tooltip"},{"id":"legend","title":"Legend"},{"id":"accessibility","title":"Accessibility"}]
    },
  "checkbox": {
      path: "src/components/xfork-ui/checkbox.tsx",
      category: "components",
      type: "ui",
      displayName: "Checkbox",
      href: "/docs/checkbox",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"}]
    },
  "collapsible": {
      path: "src/components/xfork-ui/collapsible.tsx",
      category: "components",
      type: "ui",
      displayName: "Collapsible",
      href: "/docs/collapsible",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"}]
    },
  "combobox": {
      path: null,
      category: "components",
      type: "extra",
      displayName: "Combobox",
      href: "/docs/combobox",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"}]
    },
  "command": {
      path: "src/components/xfork-ui/command.tsx",
      category: "components",
      type: "ui",
      displayName: "Command",
      href: "/docs/command",
      sections: [{"id":"about","title":"About"},{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"},{"id":"changelog","title":"Changelog"}]
    },
  "context-menu": {
      path: "src/components/xfork-ui/context-menu.tsx",
      category: "components",
      type: "ui",
      displayName: "Context Menu",
      href: "/docs/context-menu",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"}]
    },
  "data-table": {
      path: null,
      category: "components",
      type: "extra",
      displayName: "Data Table",
      href: "/docs/data-table",
      sections: [{"id":"introduction","title":"Introduction"},{"id":"table-of-contents","title":"Table of Contents"},{"id":"installation","title":"Installation"},{"id":"prerequisites","title":"Prerequisites"},{"id":"project-structure","title":"Project Structure"},{"id":"basic-table","title":"Basic Table"},{"id":"cell-formatting","title":"Cell Formatting"},{"id":"row-actions","title":"Row Actions"},{"id":"pagination","title":"Pagination"},{"id":"sorting","title":"Sorting"},{"id":"filtering","title":"Filtering"},{"id":"visibility","title":"Visibility"},{"id":"row-selection","title":"Row Selection"},{"id":"reusable-components","title":"Reusable Components"}]
    },
  "date-picker": {
      path: null,
      category: "components",
      type: "extra",
      displayName: "Date Picker",
      href: "/docs/date-picker",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"}]
    },
  "dialog": {
      path: "src/components/xfork-ui/dialog.tsx",
      category: "components",
      type: "ui",
      displayName: "Dialog",
      href: "/docs/dialog",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"},{"id":"notes","title":"Notes"}]
    },
  "drawer": {
      path: "src/components/xfork-ui/drawer.tsx",
      category: "components",
      type: "ui",
      displayName: "Drawer",
      href: "/docs/drawer",
      sections: [{"id":"about","title":"About"},{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"}]
    },
  "dropdown-menu": {
      path: "src/components/xfork-ui/dropdown-menu.tsx",
      category: "components",
      type: "ui",
      displayName: "Dropdown Menu",
      href: "/docs/dropdown-menu",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"},{"id":"changelog","title":"Changelog"}]
    },
  "form": {
      path: "src/components/xfork-ui/form.tsx",
      category: "components",
      type: "ui",
      displayName: "Form",
      href: "/docs/form",
      sections: [{"id":"features","title":"Features"},{"id":"anatomy","title":"Anatomy"},{"id":"example","title":"Example"},{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"}]
    },
  "hover-card": {
      path: "src/components/xfork-ui/hover-card.tsx",
      category: "components",
      type: "ui",
      displayName: "Hover Card",
      href: "/docs/hover-card",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"}]
    },
  "input-otp": {
      path: "src/components/xfork-ui/input-otp.tsx",
      category: "components",
      type: "ui",
      displayName: "Input Otp",
      href: "/docs/input-otp",
      sections: [{"id":"about","title":"About"},{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"},{"id":"changelog","title":"Changelog"}]
    },
  "input": {
      path: "src/components/xfork-ui/input.tsx",
      category: "components",
      type: "ui",
      displayName: "Input",
      href: "/docs/input",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"}]
    },
  "label": {
      path: "src/components/xfork-ui/label.tsx",
      category: "components",
      type: "ui",
      displayName: "Label",
      href: "/docs/label",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"}]
    },
  "menubar": {
      path: "src/components/xfork-ui/menubar.tsx",
      category: "components",
      type: "ui",
      displayName: "Menubar",
      href: "/docs/menubar",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"}]
    },
  "navigation-menu": {
      path: "src/components/xfork-ui/navigation-menu.tsx",
      category: "components",
      type: "ui",
      displayName: "Navigation Menu",
      href: "/docs/navigation-menu",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"}]
    },
  "pagination": {
      path: "src/components/xfork-ui/pagination.tsx",
      category: "components",
      type: "ui",
      displayName: "Pagination",
      href: "/docs/pagination",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"}]
    },
  "popover": {
      path: "src/components/xfork-ui/popover.tsx",
      category: "components",
      type: "ui",
      displayName: "Popover",
      href: "/docs/popover",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"}]
    },
  "progress": {
      path: "src/components/xfork-ui/progress.tsx",
      category: "components",
      type: "ui",
      displayName: "Progress",
      href: "/docs/progress",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"},{"id":"props","title":"Props"}]
    },
  "radio-group": {
      path: "src/components/xfork-ui/radio-group.tsx",
      category: "components",
      type: "ui",
      displayName: "Radio Group",
      href: "/docs/radio-group",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"}]
    },
  "react-hook-form": {
      path: null,
      category: "components",
      type: "extra",
      displayName: "React Hook Form",
      href: "/docs/react-hook-form",
      sections: [{"id":"features","title":"Features"},{"id":"anatomy","title":"Anatomy"},{"id":"example","title":"Example"},{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"}]
    },
  "resizable": {
      path: "src/components/xfork-ui/resizable.tsx",
      category: "components",
      type: "ui",
      displayName: "Resizable",
      href: "/docs/resizable",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"},{"id":"props","title":"Props"}]
    },
  "scroll-area": {
      path: "src/components/xfork-ui/scroll-area.tsx",
      category: "components",
      type: "ui",
      displayName: "Scroll Area",
      href: "/docs/scroll-area",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"},{"id":"props","title":"Props"}]
    },
  "select": {
      path: "src/components/xfork-ui/select.tsx",
      category: "components",
      type: "ui",
      displayName: "Select",
      href: "/docs/select",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"},{"id":"changelog","title":"Changelog"}]
    },
  "separator": {
      path: "src/components/xfork-ui/separator.tsx",
      category: "components",
      type: "ui",
      displayName: "Separator",
      href: "/docs/separator",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"},{"id":"props","title":"Props"}]
    },
  "sheet": {
      path: "src/components/xfork-ui/sheet.tsx",
      category: "components",
      type: "ui",
      displayName: "Sheet",
      href: "/docs/sheet",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"},{"id":"props","title":"Props"}]
    },
  "skeleton": {
      path: "src/components/xfork-ui/skeleton.tsx",
      category: "components",
      type: "ui",
      displayName: "Skeleton",
      href: "/docs/skeleton",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"},{"id":"props","title":"Props"},{"id":"examples","title":"Examples"}]
    },
  "slider": {
      path: "src/components/xfork-ui/slider.tsx",
      category: "components",
      type: "ui",
      displayName: "Slider",
      href: "/docs/slider",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"},{"id":"props","title":"Props"}]
    },
  "switch": {
      path: "src/components/xfork-ui/switch.tsx",
      category: "components",
      type: "ui",
      displayName: "Switch",
      href: "/docs/switch",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"},{"id":"props","title":"Props"}]
    },
  "table": {
      path: "src/components/xfork-ui/table.tsx",
      category: "components",
      type: "ui",
      displayName: "Table",
      href: "/docs/table",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"},{"id":"props","title":"Props"}]
    },
  "tabs": {
      path: "src/components/xfork-ui/tabs.tsx",
      category: "components",
      type: "ui",
      displayName: "Tabs",
      href: "/docs/tabs",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"},{"id":"props","title":"Props"}]
    },
  "textarea": {
      path: "src/components/xfork-ui/textarea.tsx",
      category: "components",
      type: "ui",
      displayName: "Textarea",
      href: "/docs/textarea",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"},{"id":"props","title":"Props"}]
    },
  "toggle-group": {
      path: "src/components/xfork-ui/toggle-group.tsx",
      category: "components",
      type: "ui",
      displayName: "Toggle Group",
      href: "/docs/toggle-group",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"},{"id":"props","title":"Props"}]
    },
  "toggle": {
      path: "src/components/xfork-ui/toggle.tsx",
      category: "components",
      type: "ui",
      displayName: "Toggle",
      href: "/docs/toggle",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"},{"id":"props","title":"Props"}]
    },
  "tooltip": {
      path: "src/components/xfork-ui/tooltip.tsx",
      category: "components",
      type: "ui",
      displayName: "Tooltip",
      href: "/docs/tooltip",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"},{"id":"examples","title":"Examples"},{"id":"props","title":"Props"}]
    },
  "typography": {
      path: null,
      category: "components",
      type: "extra",
      displayName: "Typography",
      href: "/docs/typography",
      sections: [{"id":"installation","title":"Installation"},{"id":"usage","title":"Usage"}]
    },
  "authentication": {
      path: null,
      category: "examples",
      type: "example",
      displayName: "Authentication",
      href: "/examples/authentication",
      sections: []
    },
  "cards": {
      path: null,
      category: "examples",
      type: "example",
      displayName: "Cards",
      href: "/examples/cards",
      sections: []
    },
  "dashboard": {
      path: null,
      category: "examples",
      type: "example",
      displayName: "Dashboard",
      href: "/examples/dashboard",
      sections: []
    },
  "forms": {
      path: null,
      category: "examples",
      type: "example",
      displayName: "Forms",
      href: "/examples/forms",
      sections: []
    },
  "mail": {
      path: null,
      category: "examples",
      type: "example",
      displayName: "Mail",
      href: "/examples/mail",
      sections: []
    },
  "music": {
      path: null,
      category: "examples",
      type: "example",
      displayName: "Music",
      href: "/examples/music",
      sections: []
    },
  "playground": {
      path: null,
      category: "examples",
      type: "example",
      displayName: "Playground",
      href: "/examples/playground",
      sections: []
    },
  "portal-components": {
      path: null,
      category: "examples",
      type: "example",
      displayName: "Portal Components",
      href: "/examples/portal-components",
      sections: []
    },
  "tasks": {
      path: null,
      category: "examples",
      type: "example",
      displayName: "Tasks",
      href: "/examples/tasks",
      sections: []
    }
  } as const;
  
  export default componentMap;
  