// This file is auto-generated by scripts/build-registry.mts
// Do not edit this file directly

export interface ComponentInfo {
  name: string;
  displayName: string;
  demo: string;
}

export const registry: Record<string, ComponentInfo> = {
  "accordion": {
    name: "accordion",
    displayName: "Accordion",
    demo: "accordion-demo.tsx"
  },
  "alert": {
    name: "alert",
    displayName: "Alert",
    demo: "alert-demo.tsx"
  },
  "alert-dialog": {
    name: "alert-dialog",
    displayName: "AlertDialog",
    demo: "alert-dialog-demo.tsx"
  },
  "aspect-ratio": {
    name: "aspect-ratio",
    displayName: "AspectRatio",
    demo: "aspect-ratio-demo.tsx"
  },
  "avatar": {
    name: "avatar",
    displayName: "Avatar",
    demo: "avatar-demo.tsx"
  },
  "badge": {
    name: "badge",
    displayName: "Badge",
    demo: "badge-demo.tsx"
  },
  "breadcrumb": {
    name: "breadcrumb",
    displayName: "Breadcrumb",
    demo: "breadcrumb-demo.tsx"
  },
  "button": {
    name: "button",
    displayName: "Button",
    demo: "button-demo.tsx"
  },
  "calendar": {
    name: "calendar",
    displayName: "Calendar",
    demo: "calendar-demo.tsx"
  },
  "card": {
    name: "card",
    displayName: "Card",
    demo: "card-demo.tsx"
  },
  "carousel": {
    name: "carousel",
    displayName: "Carousel",
    demo: "carousel-demo.tsx"
  },
  "chart": {
    name: "chart",
    displayName: "Chart",
    demo: "chart-demo.tsx"
  },
  "chart-area": {
    name: "chart-area",
    displayName: "ChartArea",
    demo: "chart-area-demo.tsx"
  },
  "chart-bar": {
    name: "chart-bar",
    displayName: "ChartBar",
    demo: "chart-bar-demo.tsx"
  },
  "chart-line": {
    name: "chart-line",
    displayName: "ChartLine",
    demo: "chart-line-demo.tsx"
  },
  "checkbox": {
    name: "checkbox",
    displayName: "Checkbox",
    demo: "checkbox-demo.tsx"
  },
  "collapsible": {
    name: "collapsible",
    displayName: "Collapsible",
    demo: "collapsible-demo.tsx"
  },
  "combobox": {
    name: "combobox",
    displayName: "Combobox",
    demo: "combobox-demo.tsx"
  },
  "command": {
    name: "command",
    displayName: "Command",
    demo: "command-demo.tsx"
  },
  "context-menu": {
    name: "context-menu",
    displayName: "ContextMenu",
    demo: "context-menu-demo.tsx"
  },
  "date-picker": {
    name: "date-picker",
    displayName: "DatePicker",
    demo: "date-picker-demo.tsx"
  },
  "dialog": {
    name: "dialog",
    displayName: "Dialog",
    demo: "dialog-demo.tsx"
  },
  "drawer": {
    name: "drawer",
    displayName: "Drawer",
    demo: "drawer-demo.tsx"
  },
  "dropdown-menu": {
    name: "dropdown-menu",
    displayName: "DropdownMenu",
    demo: "dropdown-menu-demo.tsx"
  },
  "form": {
    name: "form",
    displayName: "Form",
    demo: "form-demo.tsx"
  },
  "forms": {
    name: "forms",
    displayName: "Forms",
    demo: "forms-demo.tsx"
  },
  "hover-card": {
    name: "hover-card",
    displayName: "HoverCard",
    demo: "hover-card-demo.tsx"
  },
  "input": {
    name: "input",
    displayName: "Input",
    demo: "input-demo.tsx"
  },
  "input-otp": {
    name: "input-otp",
    displayName: "InputOtp",
    demo: "input-otp-demo.tsx"
  },
  "label": {
    name: "label",
    displayName: "Label",
    demo: "label-demo.tsx"
  },
  "menubar": {
    name: "menubar",
    displayName: "Menubar",
    demo: "menubar-demo.tsx"
  },
  "navigation-menu": {
    name: "navigation-menu",
    displayName: "NavigationMenu",
    demo: "navigation-menu-demo.tsx"
  },
  "pagination": {
    name: "pagination",
    displayName: "Pagination",
    demo: "pagination-demo.tsx"
  },
  "popover": {
    name: "popover",
    displayName: "Popover",
    demo: "popover-demo.tsx"
  },
  "progress": {
    name: "progress",
    displayName: "Progress",
    demo: "progress-demo.tsx"
  },
  "radio-group": {
    name: "radio-group",
    displayName: "RadioGroup",
    demo: "radio-group-demo.tsx"
  },
  "resizable": {
    name: "resizable",
    displayName: "Resizable",
    demo: "resizable-demo.tsx"
  },
  "scroll-area": {
    name: "scroll-area",
    displayName: "ScrollArea",
    demo: "scroll-area-demo.tsx"
  },
  "select": {
    name: "select",
    displayName: "Select",
    demo: "select-demo.tsx"
  },
  "separator": {
    name: "separator",
    displayName: "Separator",
    demo: "separator-demo.tsx"
  },
  "sheet": {
    name: "sheet",
    displayName: "Sheet",
    demo: "sheet-demo.tsx"
  },
  "skeleton": {
    name: "skeleton",
    displayName: "Skeleton",
    demo: "skeleton-demo.tsx"
  },
  "slider": {
    name: "slider",
    displayName: "Slider",
    demo: "slider-demo.tsx"
  },
  "sonner": {
    name: "sonner",
    displayName: "Sonner",
    demo: "sonner-demo.tsx"
  },
  "switch": {
    name: "switch",
    displayName: "Switch",
    demo: "switch-demo.tsx"
  },
  "table": {
    name: "table",
    displayName: "Table",
    demo: "table-demo.tsx"
  },
  "tabs": {
    name: "tabs",
    displayName: "Tabs",
    demo: "tabs-demo.tsx"
  },
  "textarea": {
    name: "textarea",
    displayName: "Textarea",
    demo: "textarea-demo.tsx"
  },
  "toggle": {
    name: "toggle",
    displayName: "Toggle",
    demo: "toggle-demo.tsx"
  },
  "toggle-group": {
    name: "toggle-group",
    displayName: "ToggleGroup",
    demo: "toggle-group-demo.tsx"
  },
  "tooltip": {
    name: "tooltip",
    displayName: "Tooltip",
    demo: "tooltip-demo.tsx"
  }
};
